INSERT INTO caretaker (name, tel_number) VALUES ('Ania', 503333434);
INSERT INTO caretaker (name, tel_number) VALUES ('Wojtek',5043833094);
INSERT INTO caretaker (name, tel_number) VALUES ('Basia', 502954454);
INSERT INTO caretaker (name, tel_number) VALUES ('Maciej', 501903748);
INSERT INTO caretaker (name, tel_number) VALUES ('Kasia', 503777384);

INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Nutka', 1, 8, 13, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 43);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Fuks', 0, 16, 13, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 3, 47);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Fliston', 0, 10, 22, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 98);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Kakaszi', 0, 4, 26, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 38);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Elza', 1, 13, 17, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 4);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Wendy', 1, 8, 31, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 6);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Tequila', 1, 4, 44, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 1, 96);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Wenus', 1, 2, 32, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 62);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Kajtuś', 0, 1, 30, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 1, 10);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES (' Lessie', 1, 11, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 36);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Fresk', 0, 13, 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 86);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Dżem', 0, 10, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 122);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Lala', 1, 11, 9, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 107);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Szczurka', 1, 15, 36, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 27);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Prima', 1, 0, 14, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 51);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Nori', 0, 3, 9, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 67);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Dżoker', 0, 3, 44, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 90);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Echo', 1, 1, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 13);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Kali', 0, 0, 8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 111);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Gandalf', 0, 9, 11, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 114);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Dżon', 0, 12, 16, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 5);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Puma', 1, 16, 52, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 1, 50);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Wera', 1, 2, 48, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 60);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Banchee', 1, 7, 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 87);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Paker', 0, 2, 7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 81);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Lady', 1, 5, 9, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 111);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Nokaut', 0, 9, 38, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 1, 13);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Adele', 1, 5, 18, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 56);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Talula', 1, 0, 29, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 90);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Elena', 1, 15, 14, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 3, 35);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Dzindzer', 0, 14, 44, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 40);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Tajga', 1, 16, 13, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 111);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Garu', 0, 9, 26, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 68);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Paco', 0, 7, 30, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 1, 96);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Papa', 0, 2, 19, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 1, 100);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Werbena', 1, 16, 15, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 61);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Kajko', 0, 0, 18, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 3, 90);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Nerd', 0, 15, 22, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 19);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Dżoj', 0, 6, 25, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 3, 64);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Pestka', 1, 12, 12, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 4, 5);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Szynszyla', 1, 12, 55, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 3, 23);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Fumfel', 0, 11, 11, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 40);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Freek', 0, 8, 6, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 5, 65);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES (' Gall', 0, 4, 10, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 3, 12);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Nimfa', 1, 15, 24, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 88);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Afera', 1, 4, 51, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 1, 4);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Dżok', 0, 1, 9, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 3, 28);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Kajtek', 0, 3, 27, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 2, 38);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Nado', 0, 13, 21, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 3, 60);
INSERT INTO dog (name, sex, age, weight, description, caretaker_id, help_count) VALUES ('Panczo', 0, 2, 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet commodo nulla facilisi nullam vehicula. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Mattis vulputate enim nulla aliquet porttitor. Diam maecenas sed enim ut. Libero nunc consequat interdum varius sit amet mattis. Tempus egestas sed sed risus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vel fringilla est ullamcorper eget. Nascetur ridiculus mus mauris vitae ultricies.

Nam libero justo laoreet sit. Arcu non sodales neque sodales ut etiam sit. Enim ut sem viverra aliquet eget sit. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Eleifend mi in nulla posuere sollicitudin. Sapien eget mi proin sed libero enim. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mauris nunc congue nisi vitae suscipit. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Lectus mauris ultrices eros in cursus turpis massa tincidunt.', 1, 104);

